# Generated by Django 3.2.7 on 2022-01-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
                ('image', models.ImageField(upload_to='categories', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated', models.DateField(auto_now=True, verbose_name='Update at')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Certification')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('materials', models.TextField(verbose_name='Materiales')),
                ('colors', models.ImageField(blank=True, null=True, upload_to='colors', verbose_name='Colores')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Detail Image')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Home Space Image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Home Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated', models.DateField(auto_now=True, verbose_name='Update at')),
                ('category', models.ManyToManyField(blank=True, to='products.Category', verbose_name='Categoria')),
                ('certifications', models.ManyToManyField(blank=True, to='products.Certification', verbose_name='Certificaciones')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
