# Generated by Django 3.2.7 on 2022-01-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220126_0309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
