# Generated by Django 3.2.7 on 2022-02-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Banner')),
                ('info', models.TextField(verbose_name='Sections info')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners')),
            ],
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Webinar')),
                ('theme', models.CharField(max_length=200, verbose_name='Spiking theme')),
                ('date', models.CharField(max_length=200, verbose_name='Date of spiking')),
            ],
        ),
    ]
