# Generated by Django 3.2.7 on 2022-02-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220207_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name=' Color'),
        ),
    ]
