# Generated by Django 3.2.7 on 2022-02-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='Image 2'),
        ),
    ]
